name: Continuous Integration

on:
  push:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        compiler: [ clang, gcc ]
        type: [ Debug, Release ]
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v3
      - name: Initialize Environment
        uses: ROOT-Sim/ci-actions/init@v1.2
      - name: Build & Test
        uses: ROOT-Sim/ci-actions/cmake@v1.2
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.compiler }}
          build-type: ${{ matrix.type }}
          run-test: true
